### PR TITLE
only override autosummary for accessor-related templates

### LINKED ISSUE #66: Error using `recursive` with `sphinx-autosummary-accessors`
I'm having some trouble using the `recursive` option while `sphinx-autosummary-accessors` is enabled. To clarify, I'm not trying to use the recursive option with the autosummary-accessor templates, but just having the recursive option enabled on other directives results in an error.

The error I see is: `ValueError: not enough values to unpack (expected 2, got 1)` on [this line](https://github.com/xarray-contrib/sphinx-autosummary-accessors/blob/758d8131604e5c4c3b26b9a38a09684fd77f9f24/sphinx_autosummary_accessors/autosummary.py#L12). An example `match` that causes the error is `[('automodule', 'dask.bag')]` when something like `[('currentmodule', 'dask'), ('autoaccessorattribute', 'dataframe.Series.cat.ordered')]`, e.g. is expected.

### PR DESCRIPTION
**Pull request by scharlottej13**
- fixes #66

There is probably a better way to fix this, but thought I'd start with a suggestion! The goal is to use autosummary from `sphinx.ext.autosummary` unless an accessor template is explicitly specified.

### CODE REVIEW

**Comment by keewis** [comment]
thanks for investigating, @scharlottej13, and sorry for answering your ping in dask/dask#8657.

I pushed a few changes to compare against a list of known templates, which might be a bit more robust, and added a "test" (I really should try to find a way to test the extension without actually running `sphinx`).

Can you confirm that this still fixes your issue?

**Comment by keewis** [comment]
great! I'll merge and create a new release, then.

**Comment by keewis** [comment]
the release is on PyPI, and once the `conda-forge` bot picks that up it should also be available from there (i.e. tomorrow at the latest).

Thanks again for the PR, @scharlottej13!

**Comment by scharlottej13** [comment]
> the release is on PyPI, and once the `conda-forge` bot picks that up it should also be available from there (i.e. tomorrow at the latest).

Perfect, thank you so much @keewis!

**Pull request merged**
